service: demo-twitter-buildmeavideo
frameworkVersion: '2 || 3'

plugins:
  - serverless-prune-plugin
  - serverless-dotenv-plugin

custom:
  project: ${self:service}
  prune:
    automatic: true
    includeLayers: true
    number: 5

provider:
  name: aws
  runtime: nodejs16.x
  stage: demo
  region: ap-southeast-2
  lambdaHashingVersion: '20201221'
  logRetentionInDays: 30
  deploymentBucket:
    name: shotstack-serverless-deploys-${self:provider.region}
    blockPublicAccess: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
        - "lambda:InvokeAsync"
      Resource:
        - "*"

package:
  exclude:
    - .env
    - .env.dist
    - .gitignore
    - README.md

functions:
  process:
    handler: handlers/twitter/handler.process
    description: Process any new mentions
    timeout: 300
    memorySize: 128
    events:
      - eventBridge:
        schedule: rate(1 minute)
  webhook:
    handler: handlers/shotstack/lib/webhook.process
    description: Respond to webhook
    timeout: 30
    memorySize: 128
    events:
      - http:
          method: POST
          path: /webhook/{id}
  reply:
    handler: handlers/twitter/handler.reply
    description: Upload rendered videos to Twitter and tweet
    timeout: 30
    memorySize: 128